```{r}
# 1 tidyverse essentials (dplyr & tidyr)

rm(list = ls())
graphics.off()

# Install packages and load package
#install.packages("tidyverse") # tidyverse packages
#install.packages("dplyr")     # individual package installation
#install.packages("tidyr")     # individual package installation
#install.packages("ggplot2")   # we need it for the data set

library(dplyr)
library(tidyr)
library(ggplot2)

# Inspect data
#help("mpg")

df <- mpg
#View(df) # check table
print(df) # print to console
str(df) # table structure
nrow(df); ncol(df) # rows ~ cols


# 1.3 Manipulate variables (columns) - select(), rename()

# select() - Columns selection

#   Extract columns car: manufacturer, model, year
select(df, manufacturer, model, year) # just extract columns
df.car.info <- select(df, manufacturer, model, year)
rm(df.car.info)

#   Extract columns that begin with letter "m"
select(df, starts_with("m"))

#   Extract columns that contain letter "r"
select(df, contains("r"))

#   Extract columns that end with letter "y"
select(df, ends_with("y"))

#   Select column by columns index
select(df, 1:3)      # first three columns
select(df, c(2,5,7)) # second, fifth and seventh column
select(df, (ncol(df)-2):ncol(df)) # last three columns


# rename() - Rename columns

#   Rename columns "manufacturer" and "model"
df1 <- rename(df, 
              mnfc = manufacturer,
              mod = model)


# select columns and rename in one take
select(df,
       mnfc = manufacturer,
       mod = model,
       everything()) # selects all other columns
``` 

# mutate(), transmute()

## mutate()

Create new variable

```{r}
#   Create variable: average between highway and city miles per gallon
df <- mutate(df,
             `avg miles per gallon` = (cty + hwy) / 2)
df#YO
#   Create variable "car" & "cyl / trans"
df <- mutate(df,
             car = paste(manufacturer, model, sep = " "),
             `cyl / trans` = paste(cyl, " cylinders", " / ", trans, " transmission", sep = ""))
df#YO
```

## transmute() 

Create new variable and drop other variables

```{r}
transmute(df,
          `avg miles per gallon` = (cty + hwy) / 2)

transmute(df,
          car = paste(manufacturer, model, sep = " "),
          `cyl / trans` = paste(cyl, " cylinders", " / ", trans, " transmission", sep = ""))
```

